# Application settings available as Rails.application.config.settings
#
# All values in this file are namespaced under Rails.application.config.settings
# and will not conflict with other configuration values in Rails.application.config.
# Settings are manually applied to the correct config var as needed in specific initializers.
# e.g. config/initializers/devise.rb

common: &common
  # Downcased and trimmed app name for namespaces.
  # Safest to start with a letter rather than a number.
  # See locales/en.yml for setting your app's user facing brand name.
  app_name: 'emailnewsletterpost'

  social:
    facebook: 'https://www.facebook.com/rememberlenny'
    twitter: 'https://twitter.com/rememberlenny'
    google_plus: 'https://plus.google.com/+rememberlenny'
    linkedin: 'http://www.linkedin.com/in/rememberlenny'

  contact:
    email: 'rememberlenny@gmail.com'
    phone: '555-555-5555'

  session:
    key: '_emailnewsletterpost_session'
    expire_after: <%= 30.days %>

  rack:
    # Timeout request after 20 seconds
    timeout: 20

  mail:
    layout: 'emails/email'
    from: 'noreply@emailnewsletterstand.com'


# Default ENV vars.
# Set to development values for convenience and override in production by setting ENV on the server.
# As a best practice, do not put production values in this file for security reasons.
default_env: &default_env
  # From address to use when sending email
  ALGOLIASEARCH_API_KEY:        a8ceec80c94969b38c848b92effd9263
  ALGOLIASEARCH_API_KEY_SEARCH:
  ALGOLIASEARCH_APPLICATION_ID: J2ELQ5BG86
  APPLICATION_HOST:             www.emailnewsletterstand.com
  ASSET_HOST:                   www.emailnewsletterstand.com
  AUTH_FACEBOOK_KEY:            918961361474155
  AUTH_FACEBOOK_SECRET:         7ffa4a656a402cb1b464d702bc2ba93a
  AUTH_TWITTER_KEY:             Sg6IbeGGgSmIsosQ8tR3ZRVLH
  AUTH_TWITTER_SECRET:          zFYNEkJ0JrJ0HssnGIsSlGTbD8ve3DfB4VLAwgTO0od237Lkvj
  DATABASE_URL:                 postgres://xofmzbqbspnflr:SUV_OtL9lrP2Et_3iPktqr7qyx@ec2-54-204-30-115.compute-1.amazonaws.com:5432/d72ls6v1bhhjgn
  DEVISE_PEPPER:                debbc13dd6add8f54df987cddf76deb7e74325578d7af07dbdfaa4072b23f9b47bbab4016353f9809918b94fc092fa600bb0428603f46df69eeb6dfc90dc6a84
  DEVISE_SECRET_KEY:            bf1b1508eebe38db8d65922ff559e3e0ec40bd52805ded6d4b2e8a0849c5c7b3510695720a7c7850d1c28908644a268815c9acf9fddef2d1028adc47656c74eb
  EMAIL_RECIPIENTS:             rememberlenny@gmail.com
  ENS_AUTH_FACEBOOK_KEY:        918961361474155
  ENS_AUTH_FACEBOOK_SECRET:     7ffa4a656a402cb1b464d702bc2ba93a
  ENS_AUTH_TWITTER_KEY:         Sg6IbeGGgSmIsosQ8tR3ZRVLH
  ENS_AUTH_TWITTER_SECRET:      zFYNEkJ0JrJ0HssnGIsSlGTbD8ve3DfB4VLAwgTO0od237Lkvj
  ENS_AWS_ACCESS_KEY_ID:        AKIAJAKM76HWMQAONAHA
  ENS_AWS_BUCKET:               emailnewsletterstand
  ENS_AWS_REGION:               us-east-1
  ENS_AWS_SECRET_ACCESS_KEY:    s2iW6o+JFfj8z48Tm0SQsSGFzQqcGHb1nEYcoUqO
  EXECJS_RUNTIME:               Node
  GOOGLE_ANALYTICS_ID:          UA-70452202-1
  LANG:                         en_US.UTF-8
  MAIL_HOST:                    emailnewsletterstand.com
  MEMCACHIER_PASSWORD:          6782a3df6bfec73f86ac70fa9328b33e
  MEMCACHIER_SERVERS:           mc1.dev.ec2.memcachier.com:11211
  MEMCACHIER_USERNAME:          86796d
  NEW_RELIC_LICENSE_KEY:        7b69123ec196f56841070f3ec1de51441e0b7975
  NEW_RELIC_LOG:                stdout
  RABBITMQ_BIGWIG_RX_URL:       amqp://dmXvIki1:MuALRXJSl15D_Bntwu2foLsT7aHHln88@curious-coltsfoot-59.bigwig.lshift.net:10719/Neqiygep2LG9
  RABBITMQ_BIGWIG_TX_URL:       amqp://dmXvIki1:MuALRXJSl15D_Bntwu2foLsT7aHHln88@curious-coltsfoot-59.bigwig.lshift.net:10718/Neqiygep2LG9
  RABBITMQ_BIGWIG_URL:          amqp://dmXvIki1:MuALRXJSl15D_Bntwu2foLsT7aHHln88@curious-coltsfoot-59.bigwig.lshift.net:10718/Neqiygep2LG9
  RACK_ENV:                     staging
  RAILS_ENV:                    production
  RAILS_SERVE_STATIC_FILES:     true
  REDISTOGO_URL:                redis://redistogo:9e07968acbe233ff3ea2df027f4f40c2@tarpon.redistogo.com:11738/
  REDIS_URL:                    redis://redistogo:9e07968acbe233ff3ea2df027f4f40c2@tarpon.redistogo.com:11738/
  ROLLBAR_ACCESS_TOKEN:         4e0d68e3dcd8450eb52895a332a9c59a
  ROLLBAR_ENDPOINT:             https://api.rollbar.com/api/1/item/
  SEARCHBOX_SSL_URL:            https://paas:265f3d5478a95c1041a6ed3561f7b73a@dwalin-us-east-1.searchly.com
  SEARCHBOX_URL:                http://paas:265f3d5478a95c1041a6ed3561f7b73a@dwalin-us-east-1.searchly.com
  SECRET_KEY_BASE:              eea3226f08328db7a7315266374e04c4f27de8d5f6e6ba25278913fdf63bbe5a8e0b5ae76cf094973b3b9a5aa0b8e1ada52c14595f509e52dc58b7a5d48c6f40
  SENDGRID_PASSWORD:            ioqrmzpt0090
  SENDGRID_USERNAME:            app43913974@heroku.com
  SMTP_ADDRESS:                 smtp.sendgrid.net
  SMTP_DOMAIN:                  emailnewsletterstand.com
  SMTP_PASSWORD:                lkbgift
  SMTP_USERNAME:                password

development:
  <<: *common
  env:
    <<: *default_env
    ALLOW_EMAIL_PREVIEW: true

test:
  <<: *common
  env:
    <<: *default_env

staging:
  <<: *common
  env:
    <<: *default_env

production:
  <<: *common
  env:
    # Set dummy key so rake assets:precompile succeeds
    DEVISE_SECRET_KEY: ''
