# Application settings available as Rails.application.config.settings
#
# All values in this file are namespaced under Rails.application.config.settings
# and will not conflict with other configuration values in Rails.application.config.
# Settings are manually applied to the correct config var as needed in specific initializers.
# e.g. config/initializers/devise.rb

common: &common
  # Downcased and trimmed app name for namespaces.
  # Safest to start with a letter rather than a number.
  # See locales/en.yml for setting your app's user facing brand name.
  app_name: 'emailnewsletterpost'

  social:
    facebook: 'https://www.facebook.com/rememberlenny'
    twitter: 'https://twitter.com/rememberlenny'
    google_plus: 'https://plus.google.com/+rememberlenny'
    linkedin: 'http://www.linkedin.com/in/rememberlenny'

  contact:
    email: 'rememberlenny@gmail.com'
    phone: '555-555-5555'

  session:
    key: '_emailnewsletterpost_session'
    expire_after: <%= 30.days %>

  rack:
    # Timeout request after 20 seconds
    timeout: 20

  mail:
    layout: 'emails/email'
    from: 'noreply@emailnewsletterstand.com'


# Default ENV vars.
# Set to development values for convenience and override in production by setting ENV on the server.
# As a best practice, do not put production values in this file for security reasons.
default_env: &default_env
  # From address to use when sending email
  ALGOLIASEARCH_APPLICATION_ID: J2ELQ5BG86
  APPLICATION_HOST:             www.emailnewsletterstand.com
  ASSET_HOST:                   www.emailnewsletterstand.com
  EXECJS_RUNTIME:               Node
  DEVISE_SECRET_KEY:            3149ba60f92e7258f4fb9f4a05bcbd5a25002a829dcb34076b979d65e2eb8ddb24192759bac59436cd7ff698b9626c84c85abf1a29e295d3bca8438a39eaf790
  GOOGLE_ANALYTICS_ID:          UA-70452202-1
  LANG:                         en_US.UTF-8
  MAIL_HOST:                    emailnewsletterstand.com
  NEW_RELIC_LOG:                stdout
  RACK_ENV:                     staging
  RAILS_ENV:                    production
  RAILS_SERVE_STATIC_FILES:     true
  SMTP_ADDRESS:                 smtp.sendgrid.net
  SMTP_DOMAIN:                  emailnewsletterstand.com
  SMTP_PASSWORD:                lkbgift
  SMTP_USERNAME:                password

development:
  <<: *common
  env:
    <<: *default_env
    ALLOW_EMAIL_PREVIEW: true

test:
  <<: *common
  env:
    <<: *default_env

staging:
  <<: *common
  env:
    <<: *default_env

production:
  <<: *common
  env:
    # Set dummy key so rake assets:precompile succeeds
    DEVISE_SECRET_KEY: ''
