require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CurationsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Curation. As you add validations to Curation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CurationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all curations as @curations" do
      curation = Curation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:curations)).to eq([curation])
    end
  end

  describe "GET show" do
    it "assigns the requested curation as @curation" do
      curation = Curation.create! valid_attributes
      get :show, {:id => curation.to_param}, valid_session
      expect(assigns(:curation)).to eq(curation)
    end
  end

  describe "GET new" do
    it "assigns a new curation as @curation" do
      get :new, {}, valid_session
      expect(assigns(:curation)).to be_a_new(Curation)
    end
  end

  describe "GET edit" do
    it "assigns the requested curation as @curation" do
      curation = Curation.create! valid_attributes
      get :edit, {:id => curation.to_param}, valid_session
      expect(assigns(:curation)).to eq(curation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Curation" do
        expect {
          post :create, {:curation => valid_attributes}, valid_session
        }.to change(Curation, :count).by(1)
      end

      it "assigns a newly created curation as @curation" do
        post :create, {:curation => valid_attributes}, valid_session
        expect(assigns(:curation)).to be_a(Curation)
        expect(assigns(:curation)).to be_persisted
      end

      it "redirects to the created curation" do
        post :create, {:curation => valid_attributes}, valid_session
        expect(response).to redirect_to(Curation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved curation as @curation" do
        post :create, {:curation => invalid_attributes}, valid_session
        expect(assigns(:curation)).to be_a_new(Curation)
      end

      it "re-renders the 'new' template" do
        post :create, {:curation => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested curation" do
        curation = Curation.create! valid_attributes
        put :update, {:id => curation.to_param, :curation => new_attributes}, valid_session
        curation.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested curation as @curation" do
        curation = Curation.create! valid_attributes
        put :update, {:id => curation.to_param, :curation => valid_attributes}, valid_session
        expect(assigns(:curation)).to eq(curation)
      end

      it "redirects to the curation" do
        curation = Curation.create! valid_attributes
        put :update, {:id => curation.to_param, :curation => valid_attributes}, valid_session
        expect(response).to redirect_to(curation)
      end
    end

    describe "with invalid params" do
      it "assigns the curation as @curation" do
        curation = Curation.create! valid_attributes
        put :update, {:id => curation.to_param, :curation => invalid_attributes}, valid_session
        expect(assigns(:curation)).to eq(curation)
      end

      it "re-renders the 'edit' template" do
        curation = Curation.create! valid_attributes
        put :update, {:id => curation.to_param, :curation => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested curation" do
      curation = Curation.create! valid_attributes
      expect {
        delete :destroy, {:id => curation.to_param}, valid_session
      }.to change(Curation, :count).by(-1)
    end

    it "redirects to the curations list" do
      curation = Curation.create! valid_attributes
      delete :destroy, {:id => curation.to_param}, valid_session
      expect(response).to redirect_to(curations_url)
    end
  end

end
